'use client';
import {useEffect,useState} from 'react';
import {Bot,Check,Headphones,Send,ArrowLeft,Tag} from 'lucide-react';
import {ChannelLogo} from './channel-chat';
const contacts=[
 {name:'Maya Chen',initials:'MC',channel:'WhatsApp',tag:'Order enquiry',preview:'Is delivery included?',question:'Is delivery included in the price?',answer:'Delivery is calculated at checkout. Share your postcode and I can help.',follow:'Can someone check my order?',human:'Hi Maya, I’m Alex. I’ll check your order and confirm the delivery cost.',color:'mint'},
 {name:'Priya Nair',initials:'PN',channel:'Instagram',tag:'New lead',preview:'I’d love to see a demo.',question:'Can I book a demo for my team?',answer:'Of course. Would tomorrow morning or afternoon work better?',follow:'Tomorrow afternoon, please.',human:'Hi Priya, I’m Alex. I’ll help arrange your team’s demo.',color:'lilac'},
 {name:'Sam Rivera',initials:'SR',channel:'Messenger',tag:'Appointment',preview:'Can I move my appointment?',question:'Can I move my appointment to Friday?',answer:'I can help with that. Would morning or afternoon suit you?',follow:'Friday morning would be great.',human:'Hi Sam, I’m Alex. I’ll check Friday’s available times for you.',color:'blue'}
];
export function FocusedInbox({stage}:{stage:number}){
 const [selected,setSelected]=useState(0),[taken,setTaken]=useState(false),[draft,setDraft]=useState(''),[reply,setReply]=useState(''),[mobileChat,setMobileChat]=useState(false);
 useEffect(()=>setMobileChat(stage===2),[stage]);
 const person=contacts[selected];const human=stage===2||taken;
 function select(i:number){setSelected(i);setTaken(false);setDraft('');setReply('');setMobileChat(true)}
 return <div className={`focused-inbox focus-stage-${stage} ${mobileChat?'focus-mobile-chat':''}`}>
 <header className="focus-title"><strong>{['Unified inbox','CRM','Human handoff','Insights'][stage]}</strong><span className="focus-demo">Illustration</span></header>
 {stage===0||stage===2?<div className="focus-conversations">
  <aside className="focus-contact-list" aria-label="Example conversations">{contacts.map((c,i)=><button className={selected===i?'is-selected':''} aria-pressed={selected===i} onClick={()=>select(i)} key={c.name}><span className={`focus-avatar ${c.color}`}>{c.initials}</span><span className="focus-contact-text"><strong>{c.name}</strong><span>{c.preview}</span><span className="focus-contact-channel"><ChannelLogo channel={c.channel}/>{c.channel}</span><em>{c.tag}</em></span></button>)}</aside>
  <div className="focus-chat"><header><button className="focus-back" aria-label="Back to conversations" onClick={()=>setMobileChat(false)}><ArrowLeft size={16}/></button><span className={`focus-avatar ${person.color}`}>{person.initials}</span><div><strong>{person.name}</strong><span>{human?'Alex Morgan · Human support':'Steps AI · Online'}</span></div><span className="focus-channel-badge" aria-label={person.channel}><ChannelLogo channel={person.channel}/></span></header>
  <div className="focus-message-list" key={`${selected}-${stage}`}><div className="focus-message customer"><small>{person.name}</small><p>{person.question}</p></div><div className="focus-message ai"><small><Bot size={13}/>Steps AI</small><p>{person.answer}</p></div>{human?<><div className="focus-handoff"><Headphones size={13}/>Alex joined · AI paused</div><div className="focus-message human"><small><span className="focus-mini-avatar">A</span>Alex Morgan</small><p>{reply||person.human}</p></div></>:<div className="focus-message customer"><small>{person.name}</small><p>{person.follow}</p></div>}</div>
  <footer>{human?<form onSubmit={event=>{event.preventDefault();if(draft.trim()){setReply(draft.trim());setDraft('')}}}><input aria-label="Demo reply" placeholder="Reply as Alex…" value={draft} onChange={e=>setDraft(e.target.value)}/><button aria-label="Send demo reply" disabled={!draft.trim()}><Send size={15}/></button></form>:<><span><Tag size={13}/>{person.tag}</span><button onClick={()=>setTaken(true)}><Headphones size={14}/>Take over</button></>}</footer></div>
 </div>:stage===1?<div className="focus-crm"><div className="focus-crm-people">{contacts.map((c,i)=><button aria-pressed={selected===i} className={selected===i?'is-selected':''} key={c.name} onClick={()=>select(i)}><span className={`focus-avatar ${c.color}`}>{c.initials}</span><strong>{c.name}</strong><span className="focus-contact-channel"><ChannelLogo channel={c.channel}/>{c.channel}</span></button>)}</div><div className="focus-customer-card"><div className="focus-customer-heading"><span className={`focus-avatar ${person.color}`}>{person.initials}</span><div><h3>{person.name}</h3><p>{person.name.toLowerCase().replace(' ','.')}@example.com</p></div><Check size={18}/></div><div className="focus-tags"><span>{person.tag}</span><span>{selected===0?'Returning customer':'Follow-up'}</span></div><dl><div><dt>Channel</dt><dd><ChannelLogo channel={person.channel}/>{person.channel}</dd></div><div><dt>Assigned to</dt><dd>Alex Morgan</dd></div><div><dt>Status</dt><dd><i/>Open conversation</dd></div></dl><div className="focus-saved"><Check size={15}/>Details saved from the conversation</div></div></div>:
 <div className="focus-insights"><div className="focus-stat-grid">{[['Conversations','248'],['Leads captured','36'],['First response','12 sec']].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="focus-chart"><h3>Where conversations happen</h3>{[['WhatsApp',124],['Instagram',78],['Messenger',46]].map(([channel,value])=><div className="focus-chart-row" key={channel}><span><ChannelLogo channel={String(channel)}/>{channel}</span><div><i style={{width:`${Number(value)/124*100}%`}}/></div><strong>{value}</strong></div>)}</div><p className="focus-example-note">Illustrative data · Last 7 days</p></div>}
 </div>
}
