'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Home,MessageSquare,Users,Bot,GitBranch,TrendingUp,ChartNoAxesCombined,Plug,BookOpen,Settings,Search,Bell,Check,Send,Headphones,ChevronDown,ArrowLeft} from 'lucide-react';
const conversations=[
{name:'Maya Chen',initials:'MC',channel:'WhatsApp',agent:'Store Support',preview:'Thanks — can a person confirm whether duties are included?',question:'Do you ship internationally? I’m ordering from Toronto.',answer:'Yes — we ship to Canada. Standard international delivery is usually 5–10 business days. Duties may be calculated at checkout depending on the order.',follow:'Thanks — can a person confirm whether duties are included in the price?',reply:'Hi Maya — I’m checking your cart now. Duties are shown separately at checkout and are not included in the listed product price.',time:'4m',handoff:true},
{name:'Jordan Lee',initials:'JL',channel:'Website',agent:'Store Support',preview:'Where can I find the order tracking link?',question:'Where can I find the order tracking link?',answer:'You can find it in your shipping confirmation email. Share your order number and I can help you find the next step.',follow:'I’ll check my email. Thank you!',reply:'Happy to help. Let us know if you need anything else.',time:'11m',handoff:false},
{name:'Priya Nair',initials:'PN',channel:'Website',agent:'Sales Assistant',preview:'I’m comparing the Studio and Pro plans.',question:'I’m comparing the Studio and Pro plans.',answer:'I can help you compare them. How many people will use the workspace, and what would you like to automate?',follow:'We have a team of six. Can someone walk us through it?',reply:'I can help arrange a walkthrough for your team.',time:'24m',handoff:true},
{name:'Sam Rivera',initials:'SR',channel:'Messenger',agent:'Booking Assistant',preview:'The appointment on Friday works for me.',question:'Do you have appointments on Friday?',answer:'Let’s find a time that works. Would morning or afternoon suit you?',follow:'Afternoon would be perfect.',reply:'I’ll help you check the available afternoon times.',time:'1h',handoff:false},
{name:'Oliver Smith',initials:'OS',channel:'Gmail',agent:'Returns Assistant',preview:'Please cancel my return request.',question:'Can I cancel my return request?',answer:'I can help with that. Please share your order number so the team can check your request.',follow:'Thank you. I’ll send it over.',reply:'Thanks, Oliver. We’ll review it with the order details.',time:'2h',handoff:false}
];
export function InboxPreview({stage=2}:{stage?:number}){
 const [active,setActive]=useState(0),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[taken,setTaken]=useState<Record<number,boolean>>({}),[resolved,setResolved]=useState<Record<number,boolean>>({}),[draft,setDraft]=useState(''),[sent,setSent]=useState<Record<number,string[]>>({}),[mobileChat,setMobileChat]=useState(false);
 const messages=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{if(stage===2&&messages.current)messages.current.scrollTop=messages.current.scrollHeight},[stage,active,sent]);
 useEffect(()=>{if(stage===2)setMobileChat(true)},[stage]);
 const isTaken=stage===2||!!taken[active]; const c=conversations[active];const visible=conversations.map((item,index)=>({...item,index})).filter(item=>item.name.toLowerCase().includes(query.toLowerCase())&&(filter!=='Human handoff'||item.handoff)&&(filter!=='Unread'||!resolved[item.index]));
 function select(i:number){setActive(i);setDraft('');setMobileChat(true)}
 function reply(){if(!draft.trim())return;setSent({...sent,[active]:[...(sent[active]||[]),draft.trim()]});setDraft('')}
 return <div className={`inbox-product ${mobileChat?'show-mobile-chat':''} ip-stage-${stage}`}>
 <aside className="ip-sidebar"><div className="ip-brand"><img src="/brands/steps-original.png" alt=""/>Steps AI</div><div className="ip-workspace"><span>AC</span><div><strong>Acme Commerce</strong><small>Workspace</small></div><ChevronDown size={12}/></div><div className="ip-nav">{[[Home,'Home'],[MessageSquare,'Conversations'],[Users,'CRM'],[Bot,'Agents'],[GitBranch,'Automation'],[TrendingUp,'Growth'],[ChartNoAxesCombined,'Reports']].map(([Icon,label])=>{const I=Icon as typeof Home;return <div key={String(label)} className={label===(stage===1?'CRM':stage===3?'Reports':'Conversations')?'ip-nav-active':''}><I size={14}/>{String(label)}</div>})}<small>RESOURCES & CONNECTIONS</small><div><Plug size={14}/>Connections</div><div><BookOpen size={14}/>Resources</div></div><div className="ip-owner"><Settings size={13}/>Workspace settings<div><span className="ip-avatar">AM</span><strong>Alex Morgan<small>Owner</small></strong></div></div></aside>
 <div className="ip-main"><div className="ip-topbar"><span>Acme Commerce <i>/</i> <b>{stage===1?'CRM':stage===3?'Reports':'Conversations'}</b></span><span className="ip-top-right"><Search size={13}/>Search workspace <Bell size={14}/></span></div>{stage===1&&<div className="ip-story-screen"><span className="ip-demo-label">Illustrative customer record</span><h3>CRM</h3><div className="ip-record-profile"><span className="ip-avatar">MC</span><div><h4>Maya Chen</h4><p>maya.chen@example.com</p></div><span className="ip-record-tag">Repeat customer</span></div><div className="ip-record-grid"><article><small>CONTACT INFORMATION</small><dl><dt>Location</dt><dd>Toronto, CA</dd><dt>Customer since</dt><dd>Mar 2025</dd><dt>Preferred channel</dt><dd>WhatsApp</dd><dt>Owner</dt><dd>Alex Morgan</dd></dl></article><article><small>ORDER CONTEXT</small><dl><dt>Open cart</dt><dd>$248.00</dd><dt>Last order</dt><dd>#AC-10482</dd><dt>Orders</dt><dd>6</dd><dt>Label</dt><dd>Repeat customer</dd></dl></article></div><article className="ip-record-ticket"><Headphones size={19}/><div><strong>Confirm duty handling</strong><p>Canadian checkout · Open ticket</p></div><span>Alex Morgan</span></article><h4>Conversation history</h4><div className="ip-record-history"><p><Check size={14}/> Delivery status <span>Sep 22 · Resolved</span></p><p><Check size={14}/> Product sizing <span>Aug 14 · Resolved</span></p></div></div>}{stage===3&&<div className="ip-story-screen"><span className="ip-demo-label">Illustrative data · not live results</span><h3>Conversation insights</h3><p>Last 7 days</p><div className="ip-report-metrics"><article><small>Conversations</small><strong>248</strong></article><article><small>Median first response</small><strong>12 sec</strong></article><article><small>Leads captured</small><strong>36</strong></article></div><article className="ip-report-chart"><h4>Customer conversations</h4><div className="ip-bars" role="img" aria-label="Example daily conversations: Monday 24, Tuesday 32, Wednesday 28, Thursday 41, Friday 38, Saturday 46, Sunday 39">{[24,32,28,41,38,46,39].map((value,i)=><div key={i}><span>{value}</span><i style={{height:value*2.3}}/><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>)}</div></article><article className="ip-report-topics"><h4>What customers ask</h4>{['Order and delivery updates','Product information','Appointments and bookings'].map((topic,i)=><p key={topic}><span>0{i+1}</span>{topic}<b>{[42,35,23][i]}%</b></p>)}</article></div>}<div className="ip-page"><div className="ip-page-heading"><div><h3>Conversations</h3><p>Review AI conversations, take over when needed and keep customer ownership clear.</p></div><span className="ip-demo-label">Interactive preview</span></div>
 <div className="ip-panel"><aside className="ip-list"><label className="ip-search"><Search size={13}/><input aria-label="Search demo conversations" placeholder="Search conversations" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ip-filters">{['All','Unread','Human handoff'].map(label=><button key={label} aria-pressed={filter===label} onClick={()=>setFilter(label)}>{label}</button>)}</div><div className="ip-list-label">All agents <span>{visible.length} conversations</span></div><div className="ip-contact-list">{visible.map(item=><button key={item.name} className={active===item.index?'ip-contact ip-contact-active':'ip-contact'} onClick={()=>select(item.index)} aria-pressed={active===item.index}><div><strong>{!resolved[item.index]&&<i/>}{item.name}</strong><small>{item.time}</small></div><p>{item.preview}</p><span>{item.channel} · {item.agent}</span>{item.handoff&&!resolved[item.index]&&<em>Human handoff</em>}{resolved[item.index]&&<em className="ip-resolved">Resolved</em>}</button>)}{!visible.length&&<p className="ip-empty">No conversations found.</p>}</div></aside>
 <div className="ip-chat"><header><button className="ip-back" onClick={()=>setMobileChat(false)} aria-label="Back to conversations"><ArrowLeft size={17}/></button><div><strong>{c.name}</strong><span className="ip-channel">{c.channel}</span><p>{resolved[active]?'Resolved':isTaken?'Assigned to you · AI replies paused':`${c.agent} is handling this conversation`}</p></div><button className="ip-resolve" onClick={()=>setResolved({...resolved,[active]:!resolved[active]})}><Check size={12}/>{resolved[active]?'Reopen':'Resolve'}</button></header><div className="ip-messages" ref={messages} key={active}><div className="ip-day">Today · Conversation started on {c.channel}</div><div className="ip-message ip-customer"><small>{c.name} <time>10:14</time></small><p>{c.question}</p></div><div className="ip-message ip-ai"><small><Bot size={12}/>{c.agent} <time>AI · 10:14</time></small><p>{c.answer}</p></div><div className="ip-message ip-customer"><small>{c.name} <time>10:16</time></small><p>{c.follow}</p></div>{c.handoff&&stage===2&&<div className="ip-handoff"><Headphones size={12}/> {c.agent} requested a human handoff</div>}{isTaken&&<div className="ip-message ip-human"><small><span className="ip-tiny-avatar">A</span>Alex Morgan <time>You · 10:19</time></small><p>{c.reply}</p></div>}{(sent[active]||[]).map((text,i)=><div className="ip-message ip-human" key={i}><small>Alex Morgan <time>You · Just now</time></small><p>{text}</p></div>)}</div><div className="ip-compose">{isTaken?<><textarea aria-label="Demo reply" placeholder={`Reply to ${c.name.split(' ')[0]} as Alex Morgan…`} value={draft} onChange={e=>setDraft(e.target.value)} rows={2}/><div><span>Demo only · nothing is sent</span><button disabled={!draft.trim()} onClick={reply}><Send size={12}/>Reply</button></div></>:<div className="ip-takeover"><span>Step in with the full conversation.</span><button onClick={()=>setTaken({...taken,[active]:true})}><Headphones size={13}/>Take over</button></div>}</div></div>
 <aside className="ip-context"><div className="ip-profile"><span className="ip-avatar">{c.initials}</span><div><strong>{c.name}</strong><small>{c.name.toLowerCase().replace(' ','.')}@example.com</small></div></div><dl><dt>Customer since</dt><dd>Mar 2025</dd><dt>Location</dt><dd>{active===0?'Toronto, CA':'—'}</dd><dt>Lifecycle</dt><dd>Repeat customer</dd></dl><h4>Order context</h4><dl><dt>Open cart</dt><dd>{active===0?'$248.00':'—'}</dd><dt>Last order</dt><dd>{active===0?'#AC-10482':'—'}</dd><dt>Orders</dt><dd>{active===0?'6':'—'}</dd></dl><h4>Conversation <span className={resolved[active]?'ip-status resolved':'ip-status'}>{resolved[active]?'Resolved':'Open'}</span></h4><p>{c.preview}</p><dl><dt>Owner</dt><dd>{isTaken?'Alex Morgan':c.agent}</dd></dl><h4>Recent conversations</h4><p>Sep 22 · Delivery status · Resolved</p><p>Aug 14 · Product sizing · Resolved</p></aside></div></div></div></div>
}
