'use client';
import { useEffect, useRef, useState } from 'react';
import { MessageSquare, Globe, Camera, Send, Check, Plus, Minus, Menu, X, Play, RotateCcw, CalendarDays, ShoppingBag, Users, FileText, GitBranch, Headphones, Search, Settings2, Inbox, Paperclip, ShieldCheck, Megaphone, BookOpen, CheckCheck } from 'lucide-react';
import copy from './copy.json';
import {HeroScene, ProductScene, ScrollPolish} from './showcase';

const stageIds=['engage','convert','support','return'];
const channelIcons=[Globe,MessageSquare,Camera,MessageSquare];
type Open={onOpen:(s:string)=>void};
function Brand(){return <a className="brand" href="#top" aria-label="Steps AI home"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><span>steps<span className="brand-ai">ai</span></span></a>}
function Action({children='Book a demo',onOpen,className=''}:Open&{children?:string;className?:string}){return <button className={`button ${className}`} onClick={()=>onOpen(children)}>{children}</button>}
function UnresolvedDialog({label,close}:{label:string;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} className="route-dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button className="icon-button close" onClick={close} aria-label="Close"><X size={22}/></button><span className="section-kicker">Design preview</span><h2>{label}</h2><p>This preview does not include that destination yet. The production page still needs to be connected.</p><button className="button" onClick={close}>Back to the preview</button></dialog>}
function Header({onOpen}:Open){const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}};document.addEventListener('keydown',esc);return()=>document.removeEventListener('keydown',esc)},[open]);return <header className="site-header"><div className="container header-inner"><Brand/><button ref={toggle} className="menu-toggle icon-button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav id="main-nav" aria-label="Main navigation" className={open?'nav open':'nav'}><a href="#product" onClick={()=>setOpen(false)}>Product</a><a href="#solutions" onClick={()=>setOpen(false)}>Solutions</a><a href="#stories" onClick={()=>setOpen(false)}>Resources</a><button onClick={()=>{setOpen(false);onOpen('Pricing')}}>Pricing</button><span className="nav-spacer"/><button onClick={()=>{setOpen(false);onOpen('Log in')}}>Log in</button><Action onOpen={onOpen}/></nav></div></header>}
function Bubble({children,customer=false,delay=0}:{children:React.ReactNode;customer?:boolean;delay?:number}){return <div className={`bubble ${customer?'customer':'agent'} sequence-item`} style={{animationDelay:`${delay}ms`}}>{children}</div>}
function Hero({onOpen}:Open){return <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="tiny-mark"/>{copy.hero.title}</div><h1>Your AI agent for marketing,<br className="desktop-break"/> sales and <span className="highlight">support.</span></h1><p className="hero-description">{copy.hero.paragraphs[1]}</p><div className="channels">{['Website','WhatsApp','Instagram','Messenger'].map((c,i)=>{const Icon=channelIcons[i];return <span key={c}><Icon size={16}/>{c}</span>})}</div><Action onOpen={onOpen}/><p className="reassurance">{copy.hero.paragraphs[4]}</p></div><HeroScene/></section>}
function Intro({title,description}:{title:string;description:string}){return <div className="section-intro"><h2>{title}</h2><p>{description}</p></div>}
function Quote({paragraphs,className=''}:{paragraphs:string[];className?:string}){return <figure className={`quote ${className}`}><blockquote>{paragraphs[0]}</blockquote><figcaption>{paragraphs[1]}</figcaption></figure>}
function JourneyStage({stage,index}:{stage:typeof copy.journey.stages[number];index:number}){const [active,setActive]=useState(0);return <article id={stageIds[index]} className={`journey-stage stage-${index}`}><div className="stage-copy"><span className="section-kicker"><span className="stage-number">0{index+1}</span>{stage.label}</span><h3>{stage.title}</h3><p className="stage-description">{stage.paragraphs[0]}</p><div className="features">{stage.items.map((item,i)=><div className={`feature ${active===i?'active':''}`} key={item.title}><h4><button id={`feature-${index}-${i}`} aria-expanded={active===i} aria-controls={`feature-panel-${index}-${i}`} onClick={()=>setActive(i)}><span>{item.title}</span>{active===i?<Minus size={18}/>:<Plus size={18}/>}</button></h4><div id={`feature-panel-${index}-${i}`} role="region" aria-labelledby={`feature-${index}-${i}`} hidden={active!==i}><p>{item.paragraphs[0]}</p></div></div>)}</div></div><div className="stage-media"><ProductScene stage={index} index={active}/>{stage.items[active].paragraphs.length>2&&<Quote paragraphs={stage.items[active].paragraphs.slice(1)} className="contextual"/>}</div></article>}
function ProductJourney({onOpen}:Open){const [current,setCurrent]=useState('engage');useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setCurrent(e.target.id)}),{rootMargin:'-15% 0px -60% 0px'});stageIds.forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);return <section id="product" className="product-section container"><Intro title={copy.journey.title} description={copy.journey.paragraphs[0]}/><nav className="journey-nav" aria-label="Customer journey">{copy.journey.stages.map((s,i)=><a key={s.label} href={`#${stageIds[i]}`} aria-current={current===stageIds[i]?'step':undefined}><span>0{i+1}</span>{s.label}</a>)}</nav>{copy.journey.stages.map((stage,index)=><JourneyStage key={stage.label} stage={stage} index={index}/>)}<div className="section-action"><Action onOpen={onOpen}/></div></section>}
function TeamOverview(){const [takeover,setTakeover]=useState(false);return <section id="team" className="team-section"><div className="container"><Intro title={copy.team.title} description={copy.team.paragraphs[0]}/><div className="inbox-window"><div className="inbox-rail"><span className="mini-mark">s</span><Inbox/><Users/><GitBranch/><Settings2/></div><div className="inbox-list"><div className="inbox-heading"><strong>Inbox</strong><Search size={16}/></div><span className="visual-label">All conversations</span>{[['JL','Jordan Lee','I’d love to speak with your team.'],['AK','Alex Kim','Can I change my appointment?'],['SR','Sam Rivera','Thanks, that answers my question.']].map(([initial,name,msg],i)=><div className={`inbox-person ${i===0?'selected':''}`} key={name}><span className="avatar">{initial}</span><div><strong>{name}</strong><span>{msg}</span></div></div>)}</div><div className="inbox-conversation"><div className="inbox-heading"><div><strong>Jordan Lee</strong><span>Website</span></div><button className={takeover?'takeover taken':'takeover'} onClick={()=>setTakeover(!takeover)}>{takeover?<Check size={15}/>:<Headphones size={15}/>} {takeover?'Return to AI':'Take over'}</button></div><Bubble customer>I’d love to speak with your team about our support setup.</Bubble><Bubble>I’ll bring in a teammate and share our conversation so you won’t need to start again.</Bubble><div className="handoff-state" role="status"><Users size={17}/>{takeover?'You’re in control. AI replies are paused.':'Conversation ready for your team'}</div><div className="composer"><span>{takeover?'You’re replying to Jordan':'Your team can take over anytime'}</span><Paperclip size={17}/></div></div><aside className="contact-panel"><span className="visual-label">Customer details</span><span className="avatar large">JL</span><strong>Jordan Lee</strong><dl><dt>Source</dt><dd>Website</dd><dt>Interested in</dt><dd>Customer support</dd><dt>Conversation</dt><dd>History included</dd></dl><span className="tag"><Check size={13}/> Context saved</span></aside></div><div className="team-capabilities">{copy.team.items.map((item,i)=>{const Icon=[Inbox,Users,Headphones,Search][i];return <article key={item.title}><Icon size={23}/><h3>{item.title}</h3><p>{item.paragraphs[0]}</p></article>})}</div></div></section>}
function Workflow(){const [tested,setTested]=useState(false);return <div className="workflow"><div className="workflow-toolbar"><span><GitBranch size={18}/> Follow-up workflow</span><button onClick={()=>setTested(!tested)}><Play size={14}/>{tested?'Reset preview':'Test workflow'}</button></div><div className="workflow-canvas"><div className="workflow-node"><MessageSquare size={20}/><div><small>Trigger</small><strong>New customer enquiry</strong></div><Check size={16}/></div><span className="wire"/><div className="workflow-node"><Users size={20}/><div><small>Action</small><strong>Ask and save details</strong></div>{tested&&<Check size={16}/>}</div><span className="wire"/><div className="workflow-node condition"><GitBranch size={20}/><div><small>Condition</small><strong>Needs a person?</strong></div></div><div className="workflow-branches"><div><span>Yes</span><div className="workflow-node"><Headphones size={19}/><strong>Notify your team</strong></div></div><div><span>No</span><div className="workflow-node"><Send size={19}/><strong>Send a reply</strong></div></div></div></div><div className="workflow-status" role="status"><Check size={16}/>{tested?'Preview complete · sample enquiry routed to your team':'Preview the flow before switching it on'}</div></div>}
function Setup({onOpen}:Open){return <section id="setup" className="setup-section container"><Intro title={copy.setup.title} description={copy.setup.paragraphs[0]}/><div className="setup-grid"><div className="setup-content">{copy.setup.items.slice(0,4).map((item,i)=>{const Icon=[FileText,Settings2,GitBranch,Play][i];return <article key={item.title}><Icon size={23}/><div><h3>{item.title}</h3><p>{item.paragraphs[0]}</p></div></article>})}</div><Workflow/></div><div id="integrations" className="integrations"><div><h3>{copy.setup.items[4].title}</h3><p>{copy.setup.items[4].paragraphs[0]}</p><button className="text-link" onClick={()=>onOpen('View all integrations')}>View all integrations</button></div><div className="integration-grid">{copy.setup.items[4].paragraphs[1].split(' | ').map((name,i)=>{const Icon=[ShoppingBag,ShoppingBag,CalendarDays,CalendarDays,Users,Headphones,FileText,BookOpen][i];return <span key={name}><Icon size={21}/>{name}</span>})}</div></div><div className="agent-page"><div><h3>{copy.setup.items[5].title}</h3><p>{copy.setup.items[5].paragraphs[0]}</p></div><div className="agent-page-mini"><Globe size={23}/><span>Your business<br/><strong>Your AI agent</strong></span><MessageSquare size={28}/></div></div></section>}
function BusinessFit({onOpen}:Open){const [active,setActive]=useState(0);return <section id="solutions" className="business-section"><div className="container"><Intro title={copy.business.title} description={copy.business.paragraphs[0]}/><div className="business-grid"><div className="industry-list" role="group" aria-label="Choose your industry">{copy.business.items.map((item,i)=><button key={item.title} aria-pressed={active===i} aria-controls={`industry-panel-${i}`} onClick={()=>setActive(i)}>{item.title}<span>{active===i?<Check size={18}/>:<Plus size={18}/>}</span></button>)}</div><div className="industry-panels">{copy.business.items.map((item,i)=><div key={item.title} id={`industry-panel-${i}`} hidden={active!==i} className="industry-panel"><span className="section-kicker">{item.title}</span><h3>{item.paragraphs[0]}</h3><p>{item.paragraphs[1]}</p><div className="industry-chat"><span className="mini-mark">s</span><span>{['Tell me what you’re looking for. I’ll help you find a good fit.','I can help with rooms, packages and booking policies.','Tell me what you need in a property and when you’d like to visit.','Tell me what you’d like to study.','Which clinic would you like to book with?','Tell me about your team and what you want to do.','Which application would you like to ask about?'][i]}</span></div></div>)}</div></div><button className="text-link" onClick={()=>onOpen('Explore solutions')}>Explore solutions</button></div></section>}
function Testimonials({onOpen}:Open){return <section id="stories" className="testimonials container"><Intro title={copy.testimonials.title} description={copy.testimonials.paragraphs[0]}/><div className="quote-grid">{copy.testimonials.items.map((item,i)=><article className={`story story-${i}`} key={item.title}><h3>{item.title}</h3><Quote paragraphs={item.paragraphs.slice(0,2)}/></article>)}</div><button className="text-link" onClick={()=>onOpen('See customer stories')}>See customer stories</button></section>}
function FAQ({onOpen}:Open){return <section id="faq" className="faq-section container"><div><span className="section-kicker">FAQ</span><h2>{copy.faq.title}</h2></div><div className="faq-list">{copy.faq.items.map((item,i)=><details key={item.title}><summary>{item.title}<Plus size={18}/></summary><p>{item.paragraphs[0]}</p>{i===6&&<button className="text-link" onClick={()=>onOpen('View pricing')}>View pricing</button>}</details>)}</div></section>}
function Footer({onOpen}:Open){const internal:Record<string,string>={Features:'#product',Channels:'#top',Integrations:'#integrations',Industries:'#solutions','Use cases':'#solutions','Customer stories':'#stories'};return <footer className="container"><div className="footer-top"><Brand/><p>{copy.footer.paragraphs[0]}</p></div><div className="footer-groups">{copy.footer.paragraphs.slice(1,7).map(group=>{const [title,links]=group.split(': ');return <div key={title}><h3>{title}</h3>{links?.split(' | ').map(label=>internal[label]?<a key={label} href={internal[label]}>{label}</a>:<button key={label} onClick={()=>onOpen(label)}>{label}</button>)}</div>})}</div><div className="footer-bottom"><span>Steps AI</span><div>{['Privacy policy','Terms of service'].map(label=><button key={label} onClick={()=>onOpen(label)}>{label}</button>)}</div></div></footer>}
export default function Home(){const [route,setRoute]=useState('');return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/><Header onOpen={setRoute}/><ScrollPolish/><main id="main"><Hero onOpen={setRoute}/><ProductJourney onOpen={setRoute}/><TeamOverview/><Setup onOpen={setRoute}/><BusinessFit onOpen={setRoute}/><Testimonials onOpen={setRoute}/><FAQ onOpen={setRoute}/><section className="final-section"><div className="container"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><h2>{copy.final.title}</h2><p>{copy.final.paragraphs[0]}</p><Action onOpen={setRoute} className="yellow"/></div></section></main><Footer onOpen={setRoute}/>{route&&<UnresolvedDialog label={route} close={()=>setRoute('')}/>}</>}



