// Illustrative states only. These are not shipped product screens or real customer data.
type Demo={title:string;channel:string;contextLabel:string;context:string;fields:string[][];chatLabel:string;question:string;answer:string;options?:string[];result:string;detail:string;footnote:string};
export const demos:Demo[][]=[[
{title:'Campaign studio',channel:'WhatsApp',contextLabel:'Campaign setup',context:'A personal message, at the right time.',fields:[['Audience','Selected customers'],['Personalisation','First name + offer'],['Schedule','Choose a send time'],['Estimated cost','Review before sending']],chatLabel:'Message preview',question:'Do you have the offer in a smaller size?',answer:'I can help you choose a size. Which item caught your eye?',result:'Keep the conversation going',detail:'Your agent answers when customers respond.',footnote:'Review audience, content and cost before sending'},
{title:'Comment to conversation',channel:'Instagram',contextLabel:'Comment trigger',context:'A public comment. A private conversation.',fields:[['Post comment','Contains “LINK”'],['Action','Send a direct message']],chatLabel:'Direct message',question:'LINK please!',answer:'Here’s the information you asked for. What would you like to know?',result:'Conversation started in DMs',detail:'Use your chosen flow for the next reply.',footnote:'Instagram comments, story responses and mentions'},
{title:'Ad to WhatsApp',channel:'WhatsApp',contextLabel:'Entry point',context:'An enquiry starts with a click.',fields:[['Source','Click-to-WhatsApp ad'],['Next action','Ask qualifying questions']],chatLabel:'New enquiry',question:'Hi, I’d like to know more about your service.',answer:'Happy to help. What are you looking for, and how can our team reach you?',result:'Details saved for follow-up',detail:'Keep the enquiry and its answers connected.',footnote:'Click-to-WhatsApp ad conversation illustration'},
{title:'Comment management',channel:'Instagram',contextLabel:'Comment inbox',context:'Keep public questions in view.',fields:[['Channel','Instagram'],['Response','AI or your team']],chatLabel:'Post comments',question:'Is this available in another size?',answer:'I can help with that. Which size are you looking for?',result:'A useful answer, in context',detail:'View, reply to and manage comments.',footnote:'Comment and response illustration'}
],[
{title:'Conversation to checkout',channel:'WhatsApp',contextLabel:'Connected catalogue',context:'Find the right fit, together.',fields:[['Customer need','A housewarming gift'],['Preference','Simple and useful']],chatLabel:'Shopping conversation',question:'I’m looking for a housewarming gift. Practical, but a little special.',answer:'A serving set could be a good fit. Would you prefer something for everyday use or entertaining?',options:['Everyday use','Entertaining'],result:'From recommendation to checkout',detail:'Add items to a cart and share a checkout link.',footnote:'Connected catalogue · WhatsApp or Instagram'},
{title:'Conversation to contact',channel:'Website',contextLabel:'Contact record',context:'Useful details, without starting over.',fields:[['Name','Jordan Lee'],['Interest','Customer support'],['Requirement','A shared team inbox']],chatLabel:'Lead conversation',question:'We need a better way to manage support.',answer:'How many people handle customer conversations on your team?',result:'Conversation attached to the lead',detail:'Save answers in your built-in CRM.',footnote:'Illustrative contact record'},
{title:'Choose a time in chat',channel:'Website',contextLabel:'Connected calendar',context:'Make room for the next conversation.',fields:[['Meeting','Product demo'],['Availability','From your calendar']],chatLabel:'Booking conversation',question:'Could we arrange a demo?',answer:'Yes. Here are the available times. Which works for you?',options:['Tuesday · 10:00','Tuesday · 14:30'],result:'An available time, ready to choose',detail:'Customers choose during the conversation.',footnote:'Illustrative availability, not a live booking'},
{title:'A thoughtful handoff',channel:'Website',contextLabel:'Routing rule',context:'Know when a person should step in.',fields:[['Enquiry','Needs specialist help'],['Action','Bring in your team']],chatLabel:'Customer conversation',question:'Can someone help with a specific requirement?',answer:'I’ll bring in a teammate and share our conversation with them.',result:'Your team has the context',detail:'Continue without starting over.',footnote:'Human takeover illustration'}
],[
{title:'Answers from your knowledge',channel:'Website',contextLabel:'Business information',context:'Your information. A useful answer.',fields:[['Source','Your website and FAQs'],['Topic','Appointments and policies']],chatLabel:'Customer question',question:'Can I reschedule my appointment?',answer:'I can help you find the rescheduling policy in our booking information.',result:'Grounded in business information',detail:'Website, FAQs and documents inform the answer.',footnote:'Actual replies depend on your information'},
{title:'Order updates in chat',channel:'WhatsApp',contextLabel:'Connected store',context:'An order question, answered in context.',fields:[['Source','Store and delivery tool'],['Order state','Ready for dispatch']],chatLabel:'Order enquiry',question:'Could you check where my order is?',answer:'Your order is ready for dispatch. The delivery update will appear when it’s available.',result:'Order context available',detail:'Use connected store and delivery information.',footnote:'Sample order state, not a live shipment'},
{title:'Conversation to ticket',channel:'Website',contextLabel:'Support request',context:'Keep the request and its context together.',fields:[['Request','Help with an order'],['Action','Create ticket and notify team']],chatLabel:'Customer request',question:'Something isn’t right with my order.',answer:'I’ll save your request and share the details with our support team.',result:'Ticket created with context',detail:'Customer details and the question stay together.',footnote:'Ticket creation illustration'},
{title:'After a missed call',channel:'WhatsApp',contextLabel:'Trigger',context:'A missed call can still become a conversation.',fields:[['Event','Missed WhatsApp call'],['Action','Send an automatic message']],chatLabel:'Follow-up message',question:'Missed voice call',answer:'Sorry we couldn’t answer your call. How can we help you here?',result:'Continue in chat',detail:'Let the customer explain what they need.',footnote:'WhatsApp missed-call follow-up'}
],[
{title:'Checkout follow-up',channel:'WhatsApp + Shopify',contextLabel:'Workflow trigger',context:'Help with what held them back.',fields:[['Event','Shopify checkout abandoned'],['Action','Send a WhatsApp reminder']],chatLabel:'Customer reply',question:'I wasn’t sure about delivery options.',answer:'I can help with that. What would you like to know before completing your order?',result:'Questions answered after the reminder',detail:'Your agent can handle the replies.',footnote:'Shopify checkout recovery on WhatsApp'},
{title:'Confirm before shipping',channel:'WhatsApp + Shopify',contextLabel:'Order workflow',context:'Check the order with your customer.',fields:[['Order type','Cash on delivery'],['Before shipping','Request confirmation']],chatLabel:'Confirmation message',question:'Please confirm your cash-on-delivery order.',answer:'Yes, please confirm my order.',result:'Customer confirmation recorded',detail:'Your team can review before dispatch.',footnote:'Shopify COD confirmation on WhatsApp'},
{title:'Welcome and review flow',channel:'Workflows',contextLabel:'Workflow template',context:'A considered follow-up, at every step.',fields:[['Start','Welcome message'],['Then','Order update'],['Follow-up','Review request']],chatLabel:'Customer follow-up',question:'My order arrived. Thank you!',answer:'We’re glad it arrived. Would you like to share how it went?',result:'Follow-up connected to the journey',detail:'Choose timing and what happens on reply.',footnote:'Illustrative workflow sequence'},
{title:'A reason to return',channel:'WhatsApp',contextLabel:'Campaign audience',context:'Relevant offers for selected customers.',fields:[['Audience','Selected customer group'],['Message','New-product update']],chatLabel:'Campaign conversation',question:'Hi Alex, something new arrived that you might like.',answer:'Can you tell me more about it?',result:'A new conversation begins',detail:'Answer questions when the customer replies.',footnote:'WhatsApp audience and campaign illustration'}
]];

