'use client';
import {useEffect,useRef,useState} from 'react';
import {Globe,MessageSquare,Camera,Check,CheckCheck,RotateCcw,CalendarDays,ChevronLeft,ChevronRight,Users,ShoppingBag,Send,FileText,GitBranch,Headphones,PhoneMissed,Ticket,Paperclip,MoreHorizontal,Search,Plus,Clock,ShieldCheck,Megaphone,BookOpen,Pause,Play} from 'lucide-react';
import {demos} from './product-demos';
import {ChannelChat,ChannelLogo} from './channel-chat';

function Mark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>}
function useEntrance(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const obs=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.classList.add('scene-entered');obs.disconnect()}},{threshold:.22});obs.observe(el);return()=>obs.disconnect()},[]);return ref}
export function ScrollPolish(){useEffect(()=>{const nodes=document.querySelectorAll('.section-intro,.setup-content article,.story,.team-capabilities article');const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');obs.unobserve(e.target)}}),{threshold:.12});nodes.forEach(node=>{node.classList.add('scroll-reveal');obs.observe(node)});return()=>{obs.disconnect();nodes.forEach(n=>n.classList.remove('scroll-reveal'))}},[]);return null}

export function HeroScene(){const [channel,setChannel]=useState(0);const [replay,setReplay]=useState(0);const [paused,setPaused]=useState(false);const ref=useEntrance();const icons=[Globe,MessageSquare,Camera,MessageSquare];return <div id="showcase" ref={ref} className={`hero-scene scene ${paused?'motion-paused':''}`}><div className="ocean-light ocean-one"/><div className="ocean-light ocean-two"/><div className="hero-scene-toolbar"><div className="scene-channel-controls" role="group" aria-label="Preview a customer channel">{['Website','WhatsApp','Instagram','Messenger'].map((name,i)=>{const Icon=icons[i];return <button key={name} aria-label={name} aria-pressed={channel===i} onClick={()=>{setChannel(i);setReplay(replay+1)}}><ChannelLogo channel={name}/><span>{name}</span></button>})}</div><div className="scene-tools"><button aria-label={paused?'Play visual motion':'Pause visual motion'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button aria-label="Replay conversation illustration" onClick={()=>setReplay(replay+1)}><RotateCcw size={16}/></button></div></div><div className="hero-scene-stage" key={`${channel}-${replay}`}><div className="conversation-window"><ChannelChat channel={['Website','WhatsApp','Instagram','Messenger'][channel]} question="Can I book a call to see how this works for my team?" answer="Of course. Tell me a little about your team and I’ll help you find a time." options={['Choose a time']}/></div><div className="hero-core"><span className="core-line left"/><div className="glass-logo"><div className="logo-face"><Mark/></div></div><span className="core-line right"/><div className="core-caption">Your AI agent</div><div className="core-pills"><span><BookOpen size={13}/> Your knowledge</span><span><Headphones size={13}/> Your team</span></div></div><div className="outcome-stack"><div className="record-sheet"><div className="record-title"><Users size={18}/><span>Customer context</span><Check size={16}/></div><div className="record-person"><span className="avatar">JL</span><div><strong>Jordan Lee</strong><span>{['Website','WhatsApp','Instagram','Messenger'][channel]} enquiry</span></div></div><div className="record-field"><span>Interested in</span><strong>Customer support</strong></div><div className="record-field"><span>Next step</span><strong>Book a team demo</strong></div><div className="record-attached"><MessageSquare size={14}/> Conversation included</div></div><div className="floating-result"><span className="success-icon"><Check size={17}/></span><div><strong>Ready for the next step</strong><span>Context saved for your team</span></div></div></div></div><div className="hero-scene-legend"><span><span>01</span>Customer question</span><span><span>02</span>A useful answer</span><span><span>03</span>A clear next step</span></div></div>}

function WindowTitle({icon:Icon,title,subtitle}:{icon:typeof Globe;title:string;subtitle?:string}){return <div className="mock-window-title"><span className="mock-icon"><Icon size={19}/></span><div><strong>{title}</strong>{subtitle&&<small>{subtitle}</small>}</div><MoreHorizontal size={19}/></div>}
function Calendar(){return <div className="mock-calendar"><div className="calendar-heading"><strong>Choose a time</strong><span><ChevronLeft size={14}/><ChevronRight size={14}/></span></div><div className="calendar-days">{['M','T','W','T','F','S','S'].map((day,i)=><span key={i}>{day}</span>)}{Array.from({length:21},(_,i)=><span key={i+7} className={i===9?'calendar-selected':''}>{i+1}</span>)}</div><div className="time-slots"><span>10:00 AM</span><span className="selected">2:30 PM <Check size={12}/></span><span>4:00 PM</span></div></div>}
function WorkflowCard({stage,index}:{stage:number;index:number}){const d=demos[stage][index];return <div className="mock-flow"><div className="mock-node"><span className="mock-icon"><GitBranch size={19}/></span><div><small>When this happens</small><strong>{d.fields[0][1]}</strong></div></div><div className="flow-connector"><span/></div><div className="mock-node"><span className="mock-icon yellow"><Clock size={19}/></span><div><small>Choose the timing</small><strong>Wait for your follow-up</strong></div></div><div className="flow-connector"><span/></div><div className="mock-node"><span className="mock-icon"><Send size={19}/></span><div><small>Then</small><strong>{d.fields[1]?.[1]??'Send a message'}</strong></div><Check size={16}/></div></div>}
export function ProductScene({stage,index}:{stage:number;index:number}){const d=demos[stage][index];const ref=useEntrance();const Icon=[Megaphone,ShoppingBag,BookOpen,GitBranch][stage];const kind=stage===1&&index===3?'handoff':stage===1&&index===2?'calendar':stage===3?'workflow':stage===2?'knowledge':stage===1&&index===1?'crm':stage===0?'campaign':'shop';return <div ref={ref} className={`product-visual polished-scene scene scene-${stage} scene-kind-${kind}`}><div className="ocean-light ocean-one"/><div className="ocean-light ocean-two"/><div className="scene-caption"><Icon size={17}/><span>{d.title}</span><span className="scene-platform">{d.channel}</span></div><div key={`${stage}-${index}`} className="demo-content layered-demo"><div className="primary-mock"><WindowTitle icon={Icon} title={kind==='handoff'?'Team routing':kind==='calendar'?'Your calendar':kind==='workflow'?'Workflow builder':kind==='knowledge'?(index===1?'Order details':index===2?'Support ticket':index===3?'Missed call':'Knowledge sources'):kind==='crm'?'Customer details':kind==='campaign'?(index===0?'New campaign':index===1?'Comment automation':index===2?'Ad enquiry':'Comment inbox'):'Connected catalogue'} subtitle={d.contextLabel}/><div className="primary-mock-body">{kind==='calendar'?<Calendar/>:kind==='workflow'?<WorkflowCard stage={stage} index={index}/>:<><h4>{d.context}</h4>{kind==='knowledge'&&index===0&&<div className="source-stack">{['Website pages','Business FAQs','Your documents'].map((name,i)=><div key={name}><FileText size={19}/><span>{name}</span><Check size={15}/></div>)}</div>}{kind==='crm'&&<div className="record-person"><span className="avatar">JL</span><div><strong>Jordan Lee</strong><span>Conversation attached</span></div></div>}{d.fields.map(([key,value])=><div className="mock-form-field" key={key}><span>{key}</span><div>{value}{key==='Audience'||key==='Schedule'?<ChevronRight size={14}/>:<Check size={13}/>}</div></div>)}{kind==='campaign'&&index===0&&<div className="campaign-token"><span>Hi <b>first_name</b>,</span><span>A message picked for you.</span></div>}{kind==='shop'&&<div className="catalogue-options"><span><ShoppingBag size={20}/><strong>Everyday use</strong></span><span><ShoppingBag size={20}/><strong>Entertaining</strong></span></div>}</>}</div></div><div className="floating-chat"><ChannelChat channel={d.channel} question={d.question} answer={d.answer} options={d.options} comments={stage===0&&index===3}/></div><div className="scene-outcome"><span className="success-icon"><Check size={17}/></span><div><strong>{d.result}</strong><span>{d.detail}</span></div></div></div><div className="scene-footnote">{d.footnote}</div></div>}


